name: AI Driven Test Case Generation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Detect Changes
        id: changes
        run: |
          git fetch origin master
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Initial commit detected. No changes to compare."
            exit 0
          fi
          git diff --name-only origin/master HEAD > changed_files.txt

      - name: Install Dependencies
        run: |
          pip install google-generativeai
          pip install python-dotenv

      - name: Generate Test Cases
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python testcase_generator.py --changed-files changed_files.txt

      - name: Run Tests
        run: |
          pip install pytest
          pytest tests/

      - name: Commit Test Cases
        run: |
          git config user.name "Grokr-gyanendra"
          git config user.email "gyanendra.shukla@datagrokr.co"
          git add tests/
          git commit -m "Automated test case generation" || echo "No changes to commit."
          git push
